language: rust
os:
  - osx
  - linux

# .NET CLI require Ubuntu 14.04
sudo: required
dist: trusty
addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - dotnet-dev-1.1.4

# .NET CLI require OSX 10.10
osx_image: xcode8.3

mono:
  - 4.4.2

dotnet: 1.0.4

script:
  - ./build.sh --verbosity diagnostic