language: rust
rust:
  - stable
os:
  - osx
  - linux

# .NET CLI require Ubuntu 14.04
sudo: required
dist: trusty
addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - dotnet-dev-1.1.7
    - musl-tools
    - libcurl4-openssl-dev
    - openssl
    - autoconf
    - g++
    - make
    - libsasl2-dev

# .NET CLI require OSX 10.10
osx_image: xcode8.3
dotnet: 1.1.7

before_install:  
  - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install openssl; brew link --force openssl; ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/; ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/; fi
before_script:
  - if test "$TRAVIS_OS_NAME" == "linux"; then curl https://www.openssl.org/source/old/1.0.2/openssl-1.0.2g.tar.gz | tar xzf - && cd openssl-1.0.2g && CC=musl-gcc ./Configure --prefix=$HOME/openssl no-dso linux-x86_64 -fPIC && make -j10 && make install && cd .. && rm -rf openssl-1.0.2g; fi
script:
  - ./build.sh --verbosity=diagnostic