# Build script
init:
  - git config --global core.autocrlf true

# Build script
build_script:
  - ps: .\build.ps1

# Tests
test: off

# Install Rust and Cargo
# (Based on from https://github.com/rust-lang/libc/blob/master/appveyor.yml)
install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host x86_64-pc-windows-msvc --default-toolchain stable -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V

# Branches to build
branches:
  # Whitelist
  only:
    - master
    - develop
    - /r/.*/
    - /release/.*/
    - /hotfix/.*/
    - /feature/.*/

# Build cache
cache:
- tools -> build.cake