[package]
name = "cakeup"
version = "0.0.1"
authors = ["Patrik Svensson <patrik@patriksvensson.se>"]

[dependencies]
clap = "2.31.1"
curl = "0.4.11"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
unzip = "0.1.0"
semver = "0.9.0"

[profile.release]
panic = 'abort'