[package]
name = "cakeup"
version = "0.1.0"
authors = ["Patrik Svensson <patrik@patriksvensson.se>"]

[dependencies]
getopts = "0.2"
curl = "0.4.11"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
unzip = "0.1.0"